apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfsgga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfsgga
  template:
    metadata:
      labels:
        app: tfsgga
    spec:
      containers:
      - image: okteto.dev/tfsgga:latest
        name: tfsgga
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "66e214aa-0a86-11ed-861d-0242ac120002"
        - name: Vless_Path
          value: "/vl5fgv8"
        - name: Vmess_UUID
          value: "66e214aa-0a86-11ed-861d-0242ac120002"
        - name: Vmess_Path
          value: "/vm6des9"
        - name: Share_Path
          value: "/v2link"
